name: Main

on:
  push:
    branches: [main]

  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  Main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - run: |
          curl https://newsapi.org/v2/top-headlines -G \
            -d language=en \
            -d pageSize=35 \
            -d apiKey=${{ secrets.NEWSAPI_KEY }} \
            -o news.json

      - uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - id: deployment
        uses: actions/deploy-pages@v1
